//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public Nullable<int> idPosts { get; set; }
        public int idUser { get; set; }
        public Nullable<int> idComment { get; set; }
        public string contentComment { get; set; }
        public string imageComment1 { get; set; }
        public string imageComment2 { get; set; }
        public string imageComment3 { get; set; }
        public string imageComment4 { get; set; }
        public Nullable<int> likeComment { get; set; }
        public Nullable<System.DateTime> dateComment { get; set; }
        public Nullable<bool> display { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Posts Posts { get; set; }
    }
}
