//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int id { get; set; }
        public Nullable<int> idSubjects { get; set; }
        public string contentDocument { get; set; }
        public string linkDocument { get; set; }
        public string imageDocument { get; set; }
        public Nullable<System.DateTime> dateUpload { get; set; }
        public string status { get; set; }
        public Nullable<bool> display { get; set; }
    
        public virtual Subjects Subjects { get; set; }
    }
}
