//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int id { get; set; }
        public int idChapter { get; set; }
        public string contentLesson { get; set; }
        public string linkLesson { get; set; }
        public string status { get; set; }
        public Nullable<bool> display { get; set; }
    
        public virtual Chapter Chapter { get; set; }
    }
}
