//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyWebEntities : DbContext
    {
        public StudyWebEntities()
            : base("name=StudyWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Classs> Classs { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Chapter> Chapter { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TypeAccount> TypeAccount { get; set; }
        public virtual DbSet<Video> Video { get; set; }
    }
}
