//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posts()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int id { get; set; }
        public int idUser { get; set; }
        public string contentPosts { get; set; }
        public string imagePosts1 { get; set; }
        public string imagePosts2 { get; set; }
        public string imagePosts3 { get; set; }
        public string imagePosts4 { get; set; }
        public Nullable<System.DateTime> datePost { get; set; }
        public Nullable<int> countLike { get; set; }
        public Nullable<int> countComment { get; set; }
        public string status { get; set; }
        public Nullable<bool> display { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
