//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int id { get; set; }
        public int idTest { get; set; }
        public string question1 { get; set; }
        public string imageQuestion1 { get; set; }
        public string imageQuestion2 { get; set; }
        public string imageQuestion3 { get; set; }
        public string imageQuestion4 { get; set; }
        public string answer1 { get; set; }
        public string answer2 { get; set; }
        public string answer3 { get; set; }
        public string answer4 { get; set; }
        public string correctAnswer { get; set; }
        public string imageAnswer1 { get; set; }
        public string imageAnswer2 { get; set; }
        public string imageAnswer3 { get; set; }
        public string imageAnswer4 { get; set; }
        public double score { get; set; }
        public string status { get; set; }
        public Nullable<bool> display { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
