//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int id { get; set; }
        public int idTest { get; set; }
        public int idUser { get; set; }
        public double score1 { get; set; }
        public Nullable<System.DateTime> dateAdd { get; set; }
        public Nullable<bool> display { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Test Test { get; set; }
    }
}
